services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bnf\SlimTypo3\:
    resource: '../Classes/*'

  Bnf\Typo3Middleware\ExtbaseMiddleware:
    class: Bnf\Typo3Middleware\ExtbaseMiddleware
    autowire: true
    autoconfigure: true
    public: true

  # TODO move to Configuration/Services.php and conditionally apply these depending on the TYPO3 branch
  # (to not add alias as of 10.4.2, as it already contains classes in core)
  Psr\Http\Message\RequestFactoryInterface:
    alias: Bnf\Typo3HttpFactory\RequestFactory
  Psr\Http\Message\ResponseFactoryInterface:
    alias: Bnf\Typo3HttpFactory\ResponseFactory
  Psr\Http\Message\ServerRequestFactoryInterface:
    alias: Bnf\Typo3HttpFactory\ServerRequestFactory
  Psr\Http\Message\StreamFactoryInterface:
    alias: Bnf\Typo3HttpFactory\StreamFactory
  Psr\Http\Message\UploadedFileFactoryInterface:
    alias: Bnf\Typo3HttpFactory\UploadedFileFactory
  Psr\Http\Message\UriFactoryInterface:
    alias: Bnf\Typo3HttpFactory\UriFactory
